"""Parity against the MATLAB reference implementation.

The fixtures in ``test/data/*.mat`` are generated by the MATLAB toolbox
(``MatlabToolboxes/ReflectanceModels``) and copied here by its ``sync-refmod``
script. They are the oracle: MATLAB is the reference implementation these
models were ported from, so a disagreement here is a bug in this package until
proven otherwise.

The suite is driven by ``test/data/matlab_fixtures.json``, so adding a model on
the MATLAB side means adding a generator there plus one entry in ``MODELS``
below — not a new test function.

Fixture layout is documented in the toolbox's ``docs/fixtures.md``. Geometry
arrives in MATLAB's ``(m, n, 3)`` image layout and is flattened here to the
``(pixels, 3)`` layout the refmod kernels take.
"""

from __future__ import annotations

import json
from pathlib import Path

import jax.numpy as jnp
import numpy as np
import pytest
from scipy.io import loadmat

from refmod.hapke import amsa, dhg_legendre_coefficients, imsa_modified_h
from refmod.lunar_lambert import lunar_lambert

DATA_DIR = Path(__file__).parent / "data"
MANIFEST = DATA_DIR / "matlab_fixtures.json"


def _load_manifest():
    if not MANIFEST.exists():
        return []
    return json.loads(MANIFEST.read_text())["cases"]


CASES = _load_manifest()


def _flat_vectors(a: np.ndarray) -> jnp.ndarray:
    """MATLAB (m, n, 3) geometry -> refmod (pixels, 3)."""
    a = np.asarray(a, dtype=float)
    if a.ndim == 2 and a.shape[-1] == 3:
        return jnp.asarray(a)
    return jnp.asarray(a.reshape(-1, 3))


def _flat_scalar(a) -> jnp.ndarray:
    return jnp.asarray(np.asarray(a, dtype=float).reshape(-1))


# --- model adapters --------------------------------------------------------
#
# Each adapter maps a fixture's sParams + geometry onto the corresponding
# refmod call. They exist because the two codebases order arguments
# differently: MATLAB takes (s, v, n, w, ...), refmod takes (w, b_n, i, e, n).


def _run_amsa(case, p):
    b_n = dhg_legendre_coefficients(float(p["b"]), float(p["c"]), 15)
    hc, bc0 = float(p.get("hc", 0.0)), float(p.get("Bc0", 0.0))
    # MATLAB disables coherent backscatter with NaN; refmod with 0.
    if not np.isfinite(hc) or not np.isfinite(bc0):
        hc, bc0 = 0.0, 0.0
    return amsa(
        _flat_scalar(case["fmW"]),
        b_n,
        _flat_vectors(case["fmS"]),
        _flat_vectors(case["fmV"]),
        _flat_vectors(case["fmN"]),
        float(p["tb"]),
        float(p["hs"]),
        float(p["Bs0"]),
        hc,
        bc0,
    )


def _run_imsa_approx_h(case, p):
    # refmod's imsa_modified_h implements the Hapke (1981) H-function, which is
    # what MATLAB's hapke_imsa uses -- see the toolbox's docs/known-issues.md.
    return imsa_modified_h(
        _flat_scalar(case["fmW"]),
        float(p["b"]),
        float(p["c"]),
        _flat_vectors(case["fmS"]),
        _flat_vectors(case["fmV"]),
        _flat_vectors(case["fmN"]),
        float(p["tb"]),
        float(p["hs"]),
        float(p["Bs0"]),
    )


def _run_lunar_lambert(case, p):
    return lunar_lambert(
        jnp.full(_flat_scalar(case["fmRefl"]).shape, float(p["rho"])),
        _flat_scalar(case["fvIncidenceRad"]),
        _flat_scalar(case["fvEmissionRad"]),
        _flat_scalar(case["fmAlphaRad"]),
    )


MODELS = {
    "hapke_amsa": _run_amsa,
    "hapke_imsa": _run_imsa_approx_h,
    "lunar_lambert_model": _run_lunar_lambert,
}

# Models present in the fixtures with no refmod counterpart yet. Listing them
# explicitly keeps them visible as skips rather than silently unexercised.
NO_PORT = {
    "hapke_imsa_modifiedH": "no port of the exact Hapke (2002) H-function IMSA",
    "hapke_amsa_int_legendre": "no port of the closed-form Legendre integrals",
}


@pytest.mark.skipif(not CASES, reason="MATLAB fixtures not synced; run sync-refmod")
@pytest.mark.parametrize("case", CASES, ids=lambda c: c["name"])
def test_matlab_parity(case):
    model = case["model"]
    if model in NO_PORT:
        pytest.skip(NO_PORT[model])
    if model not in MODELS:
        pytest.skip(f"no adapter for {model}")

    path = DATA_DIR / case["file"]
    if not path.exists():
        pytest.skip(f"{case['file']} not synced")

    data = loadmat(path, simplify_cells=True)["sCase"]
    params = data["sParams"]

    got = np.asarray(MODELS[model](data, params))
    expected = np.asarray(data["fmRefl"], dtype=float).reshape(-1)

    # MATLAB writes 0 for geometry below the local horizon; refmod writes NaN.
    # Both mean "no valid observation", so compare only where MATLAB produced a
    # value and refmod agrees the pixel is valid.
    finite = np.isfinite(got)
    invalid_in_matlab = expected == 0.0
    compare = finite & ~invalid_in_matlab

    assert compare.sum() > 0, "no comparable pixels in this fixture"

    # refmod must not claim a value where MATLAB masked the geometry out.
    leaked = finite & invalid_in_matlab & (np.abs(np.nan_to_num(got)) > 1e-12)
    assert not leaked.any(), (
        f"{leaked.sum()} pixel(s) where MATLAB masked the geometry but refmod "
        "returned a non-zero value"
    )

    np.testing.assert_allclose(
        got[compare],
        expected[compare],
        rtol=case["rtol"],
        atol=case["atol"],
        err_msg=(
            f"{case['name']}: refmod disagrees with the MATLAB reference "
            f"({model}, generated by MATLAB {data['strMatlabRel']} at "
            f"{data['strGitSha']})"
        ),
    )


@pytest.mark.skipif(not CASES, reason="MATLAB fixtures not synced; run sync-refmod")
def test_manifest_and_fixtures_agree():
    """Every manifest entry must have its file, and vice versa."""
    listed = {c["file"] for c in CASES}
    present = {p.name for p in DATA_DIR.glob("*.mat")} & listed
    missing = listed - present
    assert not missing, f"manifest lists fixtures that were not synced: {sorted(missing)}"
